server-port=25566
level-name=sorim-movement-lab
level-type=minecraft:flat
generator-settings={"biome":"minecraft:plains","layers":[{"block":"minecraft:bedrock","height":1},{"block":"minecraft:dirt","height":2},{"block":"minecraft:grass_block","height":1}],"structures":{"structures":{}}}
generate-structures=false
gamemode=creative
force-gamemode=false
difficulty=peaceful
online-mode=false
spawn-protection=0
enable-command-block=true
view-distance=8
simulation-distance=8
motd=Sorim Movement Lab
