server-port=25565
level-name=sorim-run-world
level-type=minecraft:normal
generate-structures=true
gamemode=survival
force-gamemode=false
difficulty=easy
online-mode=false
spawn-protection=0
enable-command-block=true
view-distance=10
simulation-distance=10
motd=Sorim Natural Run Server
